---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Load libraries

```{r}
quiet <- suppressPackageStartupMessages

quiet(library(tidyverse))
theme_set(theme_classic())
quiet(library(GGally))
quiet(library(shiny))
quiet(library(plotly))
quiet(library(ggforce))
quiet(library(ggsignif))
quiet(library(rstatix))
quiet(library(ggpubr))
```

# Setup the data, and write cached data

```{r fig.height=10}
rdf <- read_tsv("../questions_and_data/five_datasets_combined.tsv") %>%
    rename(
        child_mort = child_mortality_17,
        mean_school_wom = mean_schoolyears_in_women_09,
        childs_per_wom = children_per_woman_17,
        health_spend = health_spending_per_person_10,
        income = income_per_person_17
    )


data_columns <- rdf %>% colnames() %>% tail(-1)
write_tsv(rdf, path = "preparsed_rdf.tsv.gz")
```

```{r}
selected_european <- c(
    "Austria", "Belgium", "Denmark", "Finland", "France", "Germany", "Ireland",
    "Italy", "Iceland", "Norway", "Netherlands", "Portugal", "Spain",
    "Sweden", "United Kingdom"
)

newly_industrialized <- c(
    "Brazil", "China", "India", "Indonesia", "Malaysia", "Mexico",
    "Philippines", "South Africa", "Thailand", "Turkey"
)

rdf$group <- map(rdf$country, function(country) {
    if (country %in% selected_european) "europe"
    else if (country %in% newly_industrialized) "new_industry"
    else "other"
}) %>% unlist()

rdf_long <- rdf %>% pivot_longer(all_of(data_columns))
```

# First quick checks

```{r fig.width=10,fig.height=10}
head(rdf_long)
ggpairs(rdf %>% select(data_columns))
rdf_long %>% ggplot(aes(x=value)) + facet_wrap(name~., scales = "free_x", ncol=3) + geom_histogram(bins=50)
```

# Shiny application draft (not run, found in separate file now, app.R)

```{r eval=FALSE}
ui <- fluidPage(
    headerPanel("Exploring Gapminder with Shiny"),
    wellPanel(
        fluidRow(
            column(4, selectInput("compare_dataset", "Compare dataset", choices = data_columns, selected = data_columns[1])),
            column(4, checkboxInput("color_on_cat", "Color on categories", value = TRUE)),
            column(4, selectInput("color", "Color", choices = data_columns, selected = data_columns[2]))
        ),
        fluidRow(
            column(4, checkboxInput("only_show_targets", "Only show target groups", value=FALSE))
        )
    ),
    fluidRow(
        fluidRow(
            column(6, plotlyOutput("scatter_out1"), style='padding-right:0px;'),
            column(6, plotlyOutput("scatter_out2"), style='padding-right:0px;'),
        ),
        fluidRow(
            column(6, plotlyOutput("scatter_out3"), style='padding-right:0px;'),
            column(6, plotlyOutput("scatter_out4"), style='padding-right:0px;')
        )
    )
)

make_scatter <- function(rdf, d1_col, d2_col, color_col) {
    
    cor_val <- cor.test(rdf[[d1_col]], rdf[[d2_col]])
    
    if (color_col == "group") {
        color_scale <- scale_color_brewer(palette="Set1")
    }
    else {
        color_scale <- scale_color_gradient(low="steelblue", high="red")
    }
    
    rdf %>% ggplot(aes_string(
        x=d1_col, 
        y=d2_col, 
        label="country", 
        color=color_col)) + 
            geom_point() +
            color_scale + 
            geom_smooth(method="lm") + 
        ggtitle(sprintf("Pearson corr: %s p-value: %s", round(cor_val$estimate, 3), round(cor_val$p.value, 3)))
}


server <- function(input, output) {
    
    datasets_wo_compare <- reactive({
        data_columns %>% discard(~.==input$compare_dataset)
    })
    
    selected_data <- reactive({
        if (input$only_show_targets) {
            rdf %>% filter(country %in% c(selected_european, newly_industrialized))
        }
        else {
            rdf
        }
    })
    
    target_color <- reactive({
        if (input$color_on_cat) {
            "group"
        }
        else {
            input$color
        }
    })
    
    output$scatter_out1 <- renderPlotly({
        make_scatter(selected_data(), input$compare_dataset, datasets_wo_compare()[1], target_color())
    })
    output$scatter_out2 <- renderPlotly({
        make_scatter(selected_data(), input$compare_dataset, datasets_wo_compare()[2], target_color())
    })
    output$scatter_out3 <- renderPlotly({
        make_scatter(selected_data(), input$compare_dataset, datasets_wo_compare()[3], target_color())
    })
    output$scatter_out4 <- renderPlotly({
        make_scatter(selected_data(), input$compare_dataset, datasets_wo_compare()[4], target_color())
    })
}

shiny::shinyApp(ui, server)
```

# Are there significant differences between the groups?

```{r fig.width=9}
stat_test_out <- rdf_long %>% 
    filter(group != "other") %>%
    group_by(name) %>%
    t_test(value~group) %>%
    adjust_pvalue() %>%
    mutate(y.position = 10)

comparisons <- list(
    c("europe", "new_industry"),
    c("europe", "other"),
    c("other", "new_industry")
)

rdf %>% 
    mutate_at(data_columns, scale) %>%
    pivot_longer(data_columns) %>% 
    ggplot(aes(x=group, y=value, color=group)) + 
        geom_boxplot() + 
        theme(axis.text.x=element_text(angle=90,vjust=0.5)) +
        geom_signif(comparisons=comparisons, map_signif_level = TRUE, color="darkgray", step_increase = .1) + 
        facet_grid(.~name) + ylim(-2, 8)

```

# Are there significant correlations?

```{r fig.width=12,fig.height=20}
combn(data_columns, 2) %>% data.frame()

europe_df <- rdf %>% filter(group=="europe")
new_ind_df <- rdf %>% filter(group=="new_industry")

make_corr_plot <- function(europe_df, new_ind_df, first_col, second_col, round_digs=2) {
    
    eu_cor <- cor.test(
        europe_df %>% pull(first_col),
        europe_df %>% pull(second_col)
    )
    
    new_ind_cor <- cor.test(
        new_ind_df %>% pull(first_col),
        new_ind_df %>% pull(second_col)
    )
    
    ggplot(
        rbind(europe_df, new_ind_df), 
        aes_string(x=first_col, y=second_col, color="group")) + 
            geom_point() + 
            geom_smooth(method="lm", formula = y~x) +
            scale_color_brewer(palette="Set1") +
            ggtitle(sprintf("cor %s (p %s) Europe\ncor %s (p %s) New ind.", 
                            round(eu_cor$estimate, round_digs), 
                            round(eu_cor$p.value, round_digs), 
                            round(new_ind_cor$estimate, round_digs), 
                            round(new_ind_cor$p.value, round_digs)))
}

plot_list <- combn(data_columns, 2) %>% 
    apply(2, function(col_vals) {
        make_corr_plot(europe_df, new_ind_df, col_vals[1], col_vals[2])
    })

ggarrange(plotlist=plot_list, ncol=3, nrow=8, common.legend = TRUE)
```


# Trying out building optimal linear model predicting child mortality

```{r}
library(leaps)

model <- child_mort ~ mean_school_wom + childs_per_wom + health_spend + income
fit <- lm(model, data=rdf)
leaps_out <- regsubsets(model, data=rdf)
summary(leaps_out)
plot(leaps_out, scale="adjr2")
```


